### PR TITLE
Added Stand First Field

### PR DESCRIPTION
**Pull request by clloyd**
Stand First field is now being trimmed and sent through to the front end. Being displayed below each article image.

Delta with Stand Field

### CODE REVIEW

**Comment by lindseydew** [comment]
Looks good :+1: nice work

**Comment by chrisfinch** [comment]
Noooo my beautiful design :-(

**Comment by lindseydew** [comment]
Sorry - should have passed this by you before thumbs upping. We can revert, if you'd like a restyle before sending out.

**Comment by chrisfinch** [comment]
What's the reason for displaying the standfirst?

**Comment by lindseydew** [comment]
Chris Moran asked for more contextual information on the items

**Pull request merged**
